### ISSUE TITLE
Intervals for private test fold

### ISSUE THREAD

**Issue by jbdel** [A2Zadeh/ACL_Challenge_HML_20#1]
Hello,

Sorry if I misunderstood something. We dont have the labels for the private test fold (obviously) but therefore we dont have the intervals either to split the videos. 
Or should we treat each video_id of the private test fold as one example ?

Thank you

**Comment by A2Zadeh** [comment]
Hi @jbdel. The identity of videos are released, however, the splits themselves are only released to individual people (and not publicly). You can email me, or the challenge organizers email, and get started from there.
